server:
  port: 8080

SARAMIN:
  ApiKey: OGvfdhi5liDBRnhwW4RoyjDFs1wG6RzZGF8oGPrCSaIGQ1pC #API 키
  Job_Mid_Cd: 2 #직무 관련 코드 (IT)
  Count: 50 #job 엘리먼트 개수

spring:
  application:
    name: crane

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

  mvc:
    hidden-method:
      filter:
        enabled: true

  datasource:
    url: ${LOCAL_DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PW}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
